CREATE DATABASE BNP
GO

USE BNP
GO


CREATE TABLE Level (
    Id INT PRIMARY KEY IDENTITY,
    Exp INT NOT NULL,
	Value INT NOT NULL,
);

CREATE TABLE Player
(
	Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Score INT NOT NULL,
    CurrentLevelId INT NOT NULL,
	FOREIGN KEY (CurrentLevelId) REFERENCES Level(Id)
);

CREATE TABLE Stat (
    PlayerId INT PRIMARY KEY,
    Wins INT DEFAULT 0 NOT NULL,
    Losses INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (PlayerId) REFERENCES Player(Id)
);