CREATE DATABASE GameData
GO

USE GameData

CREATE TABLE Players (
    Id INT NOT NULL PRIMARY KEY,
    Login NVARCHAR(256) NOT NULL UNIQUE,
    Password NVARCHAR(256) NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Score INT NOT NULL,
    Exp INT NOT NULL
)